using MongoDB.Bson.Serialization.Attributes;

namespace Iimst.Api.Data;

public class Student
{
    [BsonId]
    [BsonRepresentation(MongoDB.Bson.BsonType.ObjectId)]
    public string Id { get; set; } = "";
    public string UserId { get; set; } = "";
    /// <summary>Unique. Autogenerated as YYYYMMDD + 3-digit random if not supplied.</summary>
    public string EnrollmentNo { get; set; } = "";
    public string FullName { get; set; } = "";
    public string? FatherName { get; set; }
    public string? MotherName { get; set; }
    public DateTime? DateOfBirth { get; set; }
    public string? Email { get; set; }
    public string? Address { get; set; }
    public string? Phone { get; set; }
    /// <summary>Course reference. Optional; Program kept for backward compatibility.</summary>
    public string? CourseId { get; set; }
    public string? Program { get; set; }
    public string? Branch { get; set; }
    public int? CurrentSemester { get; set; }
    public string? PhotoUrl { get; set; }
    public string? BloodGroup { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? UpdatedAt { get; set; }
}
