const employee = {
    GET_EMPLOYEES: 'GET_EMPLOYEES',
    GET_EMPLOYEE: 'GET_EMPLOYEE',
    ADD_EMPLOYEES: 'ADD_EMPLOYEES',
    EDIT_EMPLOYEE: 'EDIT_EMPLOYEE',
    DELETE_EMPLOYEE: 'DELETE_EMPLOYEE',
}
export default employee;